# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: fherbine <fherbine@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/01/08 17:00:23 by fherbine          #+#    #+#              #
#    Updated: 2018/01/08 17:27:02 by fherbine         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CHK_SRC_PATH = ./ch_sources
CHK_HEADER_PATH = ./ch_includes/
P_S_SRC_PATH = ./ps_sources
P_S_HEAD_PATH = ./ps_includes/
DEBUG_PATH = ./debug/
CHK_SRC_NAME = main.c checker.c
CHK_OBJ_NAME = $(CHK_SRC_NAME:.c=.o)
P_S_SRC_NAME = main.c push_swap.c
P_S_OBJ_NAME = $(P_S_SRC_NAME:.c=.o)
CHK_SRC = $(addprefix $(CHK_SRC_PATH)/,$(CHK_SRC_NAME))
P_S_SRC = $(addprefix $(P_S_SRC_PATH)/,$(P_S_SRC_NAME))
